theme: minima
title: We are helpers!
author: Praduman Amroliya
email: praduman.am005@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I'm Praduman, Founder of Helpers. Let's talk about our purpose.
  We gonna help everyone who is needy by the peeople who wants to help with 
  enthusiasm. We encourage people to go beyond the limits in the field of helping soul.
  Thank you. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  PradumanAmroliya # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
